import { defineConfig } from 'oxlint'

export { defineConfig }

export function getConfig() {
	return defineConfig({
		plugins: ['typescript', 'import', 'unicorn'],
		env: {
			builtin: true,
			es2018: true,
		},
		ignorePatterns: [
			'.*.{js,cjs}',
			'**/*.{js,cjs}',
			'**/node_modules/**',
			'**/dist/**',
			'**/dist2/**',
			'**/dagger/sdk/**',
			'eslint.config.ts',
			'**/eslint.config.ts',
			'**/worker-configuration.d.ts',
			'1projects/eemailme/1apps/email-scm-dash/build/**',
			'**/.wrangler/',
			'**/.dev.vars',
			'**/.astro/',
			'**/node_modules/',
			'**/.pnpm-store/',
			'**/.pnp/',
			'**/.pnp.js/',
			'**/.env',
			'**/.env.local',
			'**/.env.development.local',
			'**/.env.test.local',
			'**/.env.production.local',
			'**/.secret',
			'**/*.env',
			'**/coverage/',
			'**/.turbo/',
			'**/.vercel/',
			'**/.next/',
			'**/out/',
			'**/dist/',
			'**/dist2/',
			'**/*.bun-build',
			'**/npm-debug.log*',
			'**/yarn-debug.log*',
			'**/yarn-error.log*',
			'**/tmp/',
			'**/.DS_Store',
			'**/*.pem',
			'**/tmp.json',
			'**/tmp.ts',
			'**/*.tmp',
			'.claude/settings.local.json',
			'**/.eslintcache',
			'**/.ruff_cache/',
			'**/.sst/',
			'**/dagger/sdk/',
			'**/.venv/',
			'**/__pycache__/',
			'**/src-tauri/gen/schemas/',
			'**/src-tauri/target/',
			'**/.nitro/',
			'**/.output/',
			'**/.tanstack/',
			'play/py/*/build/',
			'play/py/**/*.egg-info/',
			'.codex/*',
			'!.codex/config.toml',
			'play/**',
		],
		rules: {
			'@typescript-eslint/no-floating-promises': 'warn',
			'import/no-named-as-default': 'warn',
			'import/no-named-as-default-member': 'warn',
			'import/no-duplicates': 'warn',
			'no-var': 'error',
			'prefer-rest-params': 'error',
			'prefer-spread': 'error',
			'eslint/prefer-const': 'warn',
			'@typescript-eslint/ban-ts-comment': 'off',
			'@typescript-eslint/no-empty-object-type': 'off',
			'typescript/await-thenable': 'off',
			'@typescript-eslint/no-explicit-any': 'off',
			'no-unused-vars': [
				'warn',
				{
					argsIgnorePattern: '^_',
					varsIgnorePattern: '^_',
				},
			],
			'@typescript-eslint/consistent-type-imports': [
				'warn',
				{
					prefer: 'type-imports',
				},
			],
			'@typescript-eslint/explicit-function-return-type': 'off',
			'@typescript-eslint/array-type': [
				'warn',
				{
					default: 'array-simple',
				},
			],
			'no-empty': 'warn',
		},
		overrides: [
			{
				files: ['**/dagger/*.ts', '**/dagger/**/*.ts'],
				rules: {
					'no-unused-vars': 'off',
				},
			},
			{
				files: ['tailwind.config.ts', 'postcss.config.mjs'],
				rules: {
					'@typescript-eslint/no-require-imports': 'off',
				},
			},
		],
	})
}
