name: Release

on:
  push:
    branches: ['main']

env:
  FORCE_COLOR: 1

jobs:
  test-and-deploy:
    name: Test and Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 10
    concurrency: ${{ github.workflow }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Install Dependencies
        run: pnpm install --frozen-lockfile --child-concurrency=10
      - name: Build
        run: pnpm turbo build
      - name: Check
        run: pnpm check
      - name: Deploy
        run: pnpm deploy

  create-release-pr:
    # For Workers, we always deploy on commits to main.
    # Release PRs are for adding changelogs only (for convenience)
    name: Create Release PR
    runs-on: ubuntu-latest
    timeout-minutes: 5
    concurrency: ${{ github.workflow }}-create-release-pr
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'pnpm'
      - name: Create Release Pull Request
        uses: changesets/action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
